mybatis:
    configuration:
        map-underscore-to-camel-case: true
    mapper-locations: classpath*:/mapper/*.xml
spring:
    datasource:
        driver-class-name: org.sqlite.JDBC
        username: root
        password: root
        url: jdbc:sqlite:@basedir@/src/main/resources/store/db/sqlite.db
    servlet:
        multipart:
            location: @basedir@/src/main/resources/store/tmp
            max-request-size: -1
            max-file-size: -1
server:
    port: 8090
CustomPath:
    resources: @basedir@src/main/resources/
    save: @basedir@/src/main/resources/store/save
    datasource: @basedir@/src/main/resources/store/db/sqlite.db
logging:
    level:
        top:
            codexvn:
                mapper:
                    trace
